name: demoalarm
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  sqflite: ^2.0.2+1
  flutter_local_notifications: ^9.5.3+1
  dotted_border: ^2.0.0+2
  provider: ^6.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300